### ISSUE TITLE
ATX publisher ignores ECUTEST var for parametrized instance

### ISSUE THREAD

**Issue by S3-D1** [jenkinsci/ecutest-plugin#73]
* mehrere ECU-TEST-Instanzen als Hilfstools konfiguriert
* TG-Instanz mit parametrierter ECU-TEST-Instanz konfigurieren
* in Pipeline ECUTEST = 'ET_ToolLabel' setzen
* startET/stopET/testProject/etc funktionieren
* publishATX kann die ECU-TEST-Instanz nicht starten
* startET - publishATX - stopET funktioniert
* TG-Konfiguration mit festem ET - publishATX funktioniert

--> publishATX sollte auch parametriert ECU-TEST korrekt starten können

**Comment by cpoenisch** [comment]
Currently the ECUTEST var must be provided as a build parameter in order to work. Will have a look for providing pipeline groovy vars or as wrapped env vars using [withEnv](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#withenv-set-environment-variables).

**Comment by cpoenisch** [comment]
Due to pending [JENKINS-29144](https://issues.jenkins-ci.org/browse/JENKINS-29144) there is no contextual environment access for a SimpleBuildStep (current implementation of all publishers and builders) as noted [here](https://jenkins.io/doc/developer/plugin-development/pipeline-integration/#variable-substitutions).
