### ISSUE TITLE
Wrong encoded tool variables using snippet generator

### ISSUE THREAD

**Issue by S3-D1** [jenkinsci/ecutest-plugin#74]
* mehrere TG-/ET-Instanzen konfigurieren
* SnippetGenerator für bspw startET oder publishATX verwenden
* Auswahl der parametrierten ToolInstanz - Dropdown-Wert ist nicht korrekt encoded
* Generat enthält '${ECUTEST}' oder '${TESTGUIDE}' -> Variable kann in der Pipeline nicht aufgelöst werden
--> Generator liefert "${ECUTEST}" oder "${TESTGUIDE}"

**Comment by cpoenisch** [comment]
The code snippet generator is misleading because it always generates snippets with single quotes for string inputs. While single quotes prevent Groovy interpolation the user is responsible for using explicit double quotes to enable string interpolation. There is currently no way for the plugin to directly interfere with generated code snippets.
